### PR TITLE
fix: (skipping) ignore track index when track uri or track uid is available

### PR DESCRIPTION
**Pull request by tooxo**
Amend to #61

### CODE REVIEW

**Comment by devgianlu** [comment]
Why is this required?

**Comment by tooxo** [comment]
> Why is this required?

For playlist and album listening this doesn't change much, but if you start a track from an album from the artists page, it loads a context with all the albums in a row, but the skipto index is only the offset relative to the album its on and not to the start of the most top album on the page.

So if you start track x from album 3 for example golibrespot would start track x from album 1 without this fix.

**Comment by tooxo** [comment]
> What a mess... Can you add a comment explaining this for future reference?

I hope the explanation is sufficient (and or comprehensible)!

**Comment by devgianlu** [comment]
Looks good!

**Pull request merged**
